### ISSUE TITLE
Autocomplete nickname on different key

### ISSUE THREAD

**Issue by pocmo** [pocmo/Yaaic#101]
I can't autocomplete nicknames on the Galaxy Nexus as it has no search key. at least when using swifkey x

**Comment by pocmo** [comment]
Long pressing the "Send" button will autocomplete the current nickname.

**Comment by eric-jahn** [comment]
> Long pressing the "Send" button will autocomplete the current nickname.

Which button is the "send" button?  I'm running yaaic on a Chromebook tablet (that runs Android Apps) with an external windows/standard (not Chromebook) keyboard.
