### ISSUE TITLE
Autoscroll to end of chatlog when meswsage arrives

### ISSUE THREAD

**Issue by hugosthlm** [pocmo/Yaaic#149]
I use Yaac v 1.0 on Cyanogenmod 10.2, Android 4.3.1 
I experience a problem. When I scroll back in the chatlog to see what was written before, as soon as a message arrives I'm autoscrolled back to last line.
I expect autoscroll only when I am at the end of the chatlog.

**Comment by pocmo** [comment]
This is fixed and will be released soonish.
