### ISSUE TITLE
 support channel of Yaaic ?

### ISSUE THREAD

**Issue by Chrysweel** [pocmo/Yaaic#161]
Hi ! 

In documentation I read as support the option channel support irc: 
>IRC: irc.epd-me.net #yaaic

But in this network, the channel is empty .. ?

There are some other channel or network support via irc?

**Comment by pocmo** [comment]
HI there. I'm sometimes there - like now. But yeah, it's mostly empty there. You can always post bugs here or on the mailing list.

**Comment by Chrysweel** [comment]
Ok thanks @pocmo  ! :)
