### ISSUE TITLE
Support Older Android 

### ISSUE THREAD

**Issue by Xenega** [pocmo/Yaaic#166]
Since the move to Gradle, Yaaic support only Lollipop. Did you decide to abandon the support of Gingerbread, JellyBean and KiKat or is it a issue to be fixed ?

**Comment by pocmo** [comment]
So, yeah, currently I'm trying to refresh the UI to a more "Material" Look & Feel. Therefore I decided to not care about older Android versions for now. As soon as this is done and released I want to get back and see whether I can backport things to Android 4+. But I do not plan to go lower than that.
