### ISSUE TITLE
Scrolldown after new message

### ISSUE THREAD

**Issue by xypron** [pocmo/Yaaic#170]
Yaaic offers to scrollback in the message history. When a new message arrives the window automaticly scroll to the bottom.

This makes it impossible to read the last few hundred messages in a high frequency chat.

Please, implement the following behavior: If the window is scrolled to the bottom and a new message is appended, scroll down. If the window is not scrolled to the bottom and a new message arrives, do not autoscroll. If the user sends a message, scroll to the bottom.

**Comment by pocmo** [comment]
This is already implemented. Are you using Yaaic 1.1 (Currently only available for Android 5+)?

**Comment by xypron** [comment]
I am using Android 4.2.2. Will all future versions require Android 5?

**Comment by pocmo** [comment]
Yaaic 2.0 will be for Android 5+ only. But after the release I'm planning to go back and see if I can backport everything back to Android 4+.
