### ISSUE TITLE
apk generated cannot be installed

### ISSUE THREAD

**Issue by codelogman** [pocmo/Yaaic#175]
Ok, i get the repository (zip file on windows), import from android studio, generate the apk and try to install it on a galaxy s5 but the installer tell me the apk is inconsistent and failed to install (is something wrong with app because the apk have 1.43 MB totally).

cheers

**Comment by pocmo** [comment]
1.43 MB sounds correct. The current version of Yaaic requires Android 5+. I assume you are running a lower version?
