### ISSUE TITLE
Permanent Android 5.0 notification on lockscreen blocks owner information from being shown

### ISSUE THREAD

**Issue by eggsgent** [pocmo/Yaaic#177]
Permanent Android 5.0 notification on lock-screen blocks owner information from being shown.

Environment: Samsung SM-G900F, Android 5.0.x
Steps:
1. Set up some form of lock-screen security, eg. a password
2. Set up your owner information to be shown on the lock-screen
3. Start Yaaic and join a channel
4. Lock the phone so it displays the lock-screen

Actual behaviour: 
1. Yaaic notification shown although no nick highlights have been made.
2. It is not possible to dismiss the notification by swiping it to one of the sides.
3. It is therefore not possible to see owner information on the lock-screen while Yaaic is running and connected to a channel

Expected behaviour: Either no notification to be shown or show a notification which can be dismissed.

**Comment by pocmo** [comment]
Thank you for the bug report. I just pushed a patch that will hide the notification from the status bar and the lock screen as long as you haven't been mentioned on a channel.

**Comment by eggsgent** [comment]
Wow, thank you so much for fixing this, and so swiftly!! Greetings from a big fan and a long time user of Yaaic.
