### ISSUE TITLE
Create and distribute alpha/beta builds via Google Play Store

### ISSUE THREAD

**Issue by pocmo** [pocmo/Yaaic#181]

**Comment by pocmo** [comment]
https://play.google.com/apps/testing/org.yaaic

**Comment by eggsgent** [comment]
Hi, the test build on Google Play crashes on startup on multiple devices, both on 5.0.x and 5.1.x. Perhaps wrong place to post this info here.

**Comment by pocmo** [comment]
No, this is fine. Feel free to even open a new issue. Thank you for testing! :)

Do you happen to have a crash log? Or did you report the issue? I'll see if I can find anything in the Play Store crash reporter.

**Comment by eggsgent** [comment]
I used the built in Report > Feedback feature with "include system logs " ticked. Let me know if you want me to gather some additional logs using adb or other logging tools.

**Comment by pocmo** [comment]
Thanks! Got a crash report and filed #185.
