### ISSUE TITLE
Replace fragment transition in MainActivity with something more sane

### ISSUE THREAD

**Issue by pocmo** [pocmo/Yaaic#184]
This 3D rotation is a bit over the top and annoying.

**Comment by eggsgent** [comment]
Hi, is the "fragment transition" eg. the 3D flip effect I see when I open the left side menu and switch between Overview and a server window? If so, the animation is also stuttering on Samsung G928F, one of the most powerful phones currently.

**Comment by pocmo** [comment]
Yeah, that's the thing. It performs okayish on the N5 but it's just totally over the top. I'll need to play with some other animations.
