### ISSUE TITLE
Channel messages notifications

### ISSUE THREAD

**Issue by Freakmeister** [pocmo/Yaaic#192]
Hey, can you please add a checkbox that will enalbe notifications of all new messages in channel? I am streaming on Twitch and I use your Android app to read chat. But I have to keep my phone on all the time and eyeball it for new messages. It would be nice if it made a sound when any new message arrive to my channel. You already have this feature for private/direct messages, can we also have it for all messages? Thanks.

**Comment by pocmo** [comment]
So you want to get a notification whenever a message is written in a channel? I guess this should not happen for join/part etc. messages?

Would it work for you if this is a global channel and is active for all channels or do you want to limit this to a particular channel?

**Comment by Freakmeister** [comment]
I don't rly care, I use Yaaic only for one channel. But I guess it would be a nice if you add notification options per channel in the future. Maybe some "loud mode" button on each channel that can be turned on and off.

**Comment by pocmo** [comment]
I added a menu option for that:

![Notify](http://i.imgur.com/MnwyvB6.png)

**Comment by zoell** [comment]
Sorry, where is this menu item exactly? I have just installed version 1.1 on a Galaxy Tab S, Android 5.0.2. If I click the menu button in a channel, I can only see Close and Disconnect.

**Comment by pocmo** [comment]
This is currently only available in beta builds. You can sign up for the beta here:
https://play.google.com/apps/testing/org.yaaic
